databases:
  - name: therialnews
    databaseName: therialnews
    user: userdb

services:
  - type: web
    name: therialnews
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: therialnews
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false